# Generated by Django 5.1.3 on 2025-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_clicks_url_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='hide_preview',
            field=models.BooleanField(default=False),
        ),
    ]
